// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/domain/market/repository.go

// Package market is a generated GoMock package.
package market

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// LastPriceBySymbol mocks base method.
func (m *MockRepository) LastPriceBySymbol(symbol string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LastPriceBySymbol", symbol)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LastPriceBySymbol indicates an expected call of LastPriceBySymbol.
func (mr *MockRepositoryMockRecorder) LastPriceBySymbol(symbol interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LastPriceBySymbol", reflect.TypeOf((*MockRepository)(nil).LastPriceBySymbol), symbol)
}
